---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    provider: "fabric8"
    project: "configmapcontroller"
    kubernetes.io/cluster-service: "true"
  name: "configmapcontroller"
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "configmapcontroller"
      provider: "fabric8"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "configmapcontroller"
    spec:
      containers:
      - image: "fabric8/configmapcontroller:2.3.5"
        name: "configmapcontroller"
